### ISSUE TITLE
unable to use env variable in credential resource: Function calls not allowed

### ISSUE THREAD

**Issue by vkumbha** [turbot/pipe-fittings#149]
Following the document: https://flowpipe.io/docs/reference/config-files/credential/abuseipdb#default-credential

I have set the environment variable: `ABUSEIPDB_API_KEY` and updated my credential.fpc file as 
```
credential "abuseipdb" "default" {
  api_key = env("ABUSEIPDB_API_KEY")
}
```

when I try to run locally, I get the below error:

```
$ flowpipe pipeline list
Error: Failed to load Flowpipe config:
Function calls not allowed: Functions may not be called here.
(/Users/venu/.flowpipe/config/credentials.fpc:6,15-39)
Unsuitable value type: Unsuitable value: value must be known
(/Users/venu/.flowpipe/config/credentials.fpc:6,15-19)
```

**Comment by vhadianto** [comment]
This is a bug @vkumbha thanks for finding. As a workaround you can just set the `ABUSEIPDB_API_KEY` environment variable. Flowpipe will automatically use that if you don't specify anything in the HCL file.
