### ISSUE TITLE
Can Flowpipe let me know if have an unsupported `credential` type?

### ISSUE THREAD

**Issue by cbruno10** [turbot/pipe-fittings#253]
If I have a creds file in my default config dir, or in my mod dir:
```hcl
cbruno@M1P ~ % cat ~/.flowpipe/config/slack.fpc
credential "slacks" "my_slack" {
  token = "xoxp-..."
}
```

Can Flowpipe let me know if I have an unsupported type (should be `slack` instead of `slacks`)?

**Comment by vhadianto** [comment]
This is covered in the latest refactoring in https://github.com/turbot/pipe-fittings/commit/3862f6ca09e90aea033b6ec186c27893a5901538

Added test case to verify: https://github.com/turbot/pipe-fittings/commit/f4e1fc3956dd3c17fbd937b63e0c53723c1b6b45
