### ISSUE TITLE
Refer to a local directory for mod dependencies?

### ISSUE THREAD

**Issue by e-gineer** [turbot/pipe-fittings#392]
While doing development of mods in flowpipe or powerpipe it's common to have mod dependencies. Unfortunately right now those dependencies must be from a github repo or similar, which makes local development more difficult than I'd like.

Suggestion, can we just accept a local directory in the `version` attribute of the mod block? For example:
```hcl
mod "aws_compliance" {
  title = "flowpipe-mod-foo"
  require {
    # local variation of a mod that often lives in github
    mod "github.com/turbot/flowpipe-mod-bar" {
      # support full paths
      version = "file:///full/path/to/local/flowpipe-mod-bar"
    }
    # purely local mod, no git ever pushed
    mod "baz" {
      # support relative paths
      version = "file:../relative/path/to/my/baz"
    }
  }
}
```

In this case we're allowing a "rootless path" variation of the `file:` scheme, which is common practice (even if not technically RFC compliant?). See https://stackoverflow.com/a/53082960

When using file based mod location I should be able to just hack away on my mod on the local machine always seeing the latest changes.

Note that mod names don't need to be in github.com/identity/repo format either - no need for that when working with local files.

**Comment by kaidaguerre** [comment]
fixed by 11eed7e21e5dfeff708a2b24f037bf8bb3c2f857
