### ISSUE TITLE
Add Guardrail credential type

### ISSUE THREAD

**Issue by luisffc** [turbot/pipe-fittings#53]
API key (https://turbot.com/guardrails/docs/guides/iam/access-keys):

```hcl
credential "guardrail" "my_guardrail" {
  access_key = "c8e2c2ed-1ca8-429b-b369-123..."
  secret_key = "a3d8385d-47f7-40c5-a90c-123..."
  workspace = "https://my_workspace.sass.turbot.com"
}
```

```hcl
credential "guardrail" "my_guardrail" {
  profile = "my_workspace"
}
```

Defaults (order of precedence): 
- If you have a default profile setup using the Turbot Guardrails CLI, Flowpipe should just works with that connection.
- `TURBOT_PROFILE ` env var
- `TURBOT_SECRET_KEY` and `TURBOT_ACCESS_KEY` `TURBOT_WORKSPACE` env var

**Comment by Subhajit97** [comment]
Added in this commit: https://github.com/turbot/pipe-fittings/pull/164
